name: Docker Image CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
jobs:
  compile:
    name: Build and push the image
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
        id-token: write # needed for signing the images with GitHub OIDC Token
    steps:
    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.1.1
    - name: Check install!
      run: cosign version
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Cache poetry dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ghcr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
        context: https://github.com/cienciadedatosysalud/cdmb.git
        file: |
          FROM python:3.9.17-slim
          RUN apt update && apt install -y --no-install-recommends \
            && apt install -y graphviz \
            && rm -rf /var/lib/apt/lists/*
          WORKDIR /app
          COPY . .
          ENV PYTHONPATH=${PYTHONPATH}:${PWD} 
          RUN pip3 install poetry
          RUN poetry config virtualenvs.create false
          RUN poetry install
          RUN echo "import cdmb\nimport os\nif __name__ == '__main__':\ncdmb.launch_ui('0.0.0.0',8501)" | cat > ui.py
          CMD ["python3", "ui.py"]
        run: |
          cosign sign ghcr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cosign verify ghcr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
