name: Docker Image CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
jobs:
  compile:
    name: Build and push the image
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
        # This is used to complete the identity challenge
        # with sigstore/fulcio when running outside of PRs.
        id-token: write
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        context: https://github.com/<owner>/<repo>.git
        file: |
          FROM python:3.9.17-slim
          RUN apt update && apt install -y --no-install-recommends \
            && apt install -y graphviz \
            && rm -rf /var/lib/apt/lists/*
          WORKDIR /app
          COPY . .
          ENV PYTHONPATH=${PYTHONPATH}:${PWD} 
          RUN pip3 install poetry
          RUN poetry config virtualenvs.create false
          RUN poetry install
          RUN echo "import cdmb\n\
          import os\n\
          if __name__ == '__main__':\n\
              cdmb.launch_ui('0.0.0.0',8501)" | cat > ui.py
          CMD ["python3", "ui.py"]
